// Generated by CoffeeScript 1.8.0
(function() {
  var WorkerClient, chai, chaiAsPromised, expect, sinon;

  chai = this.chai;

  chai.should();

  expect = chai.expect;

  chaiAsPromised = this.chaiAsPromised;

  chai.use(chaiAsPromised);

  sinon = this.sinon;

  WorkerClient = this.WorkerClient;

  describe('webworker', function() {
    var client;
    client = null;
    beforeEach(function() {
      var worker;
      worker = new Worker('./webworker_server.js');
      return client = new WorkerClient(worker);
    });
    return it('should work', function() {
      client.request('test1', ['test', 1]).should.eventually.equal('ok');
      return client.request('test1', 1).should.rejectedWith('ng');
    });
  });

}).call(this);
