// Generated by CoffeeScript 1.10.0
(function() {
  var InlineWorkerClient,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  InlineWorkerClient = (function(superClass) {
    extend(InlineWorkerClient, superClass);

    function InlineWorkerClient(worker_code, revoke_url_on_terminate, worker_error_handler) {
      var url;
      if (revoke_url_on_terminate == null) {
        revoke_url_on_terminate = false;
      }
      url = URL.createObjectURL(new Blob([worker_code], {
        type: "text/javascript"
      }));
      InlineWorkerClient.__super__.constructor.call(this, url, revoke_url_on_terminate, worker_error_handler);
    }

    return InlineWorkerClient;

  })(URLWorkerClient);

  if (typeof window !== "undefined" && window !== null) {
    window.InlineWorkerClient = InlineWorkerClient;
  }

}).call(this);
