// Generated by CoffeeScript 1.9.2
(function() {
  this.SingleFileWorkerRunner = (function() {
    function SingleFileWorkerRunner() {}

    SingleFileWorkerRunner.prototype.run = function(worker_code, client_function, worker_type) {
      if (worker_type == null) {
        worker_type = (typeof require !== "undefined" && require !== null ? 'fork' : 'webworker');
      }
      if (typeof window !== "undefined" && window !== null) {
        return client_function(worker_type === 'fork' ? this.main_fork() : this.main_webworker(worker_code));
      } else {
        return this.child(worker_code);
      }
    };

    SingleFileWorkerRunner.prototype.main_fork = function() {
      var child_process, error, scriptname;
      child_process = require('child_process');
      try {
        throw new Error();
      } catch (_error) {
        error = _error;
        scriptname = error.stack.match(/\w+:\/\/+[^\/]+\/[^:]+/)[0];
      }
      return function() {
        return child_process.fork(scriptname);
      };
    };

    SingleFileWorkerRunner.prototype.main_webworker = function(worker_code) {
      var worker_url;
      worker_url = URL.createObjectURL(new Blob([worker_code], {
        type: "text/javascript"
      }));
      return function() {
        return new Worker(worker_url);
      };
    };

    SingleFileWorkerRunner.prototype.child = function(worker_code) {
      return eval(worker_code);
    };

    return SingleFileWorkerRunner;

  })();

  if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
    module.exports = this.SingleFileWorkerRunner;
  }

}).call(this);
